### ISSUE TITLE
Add status monitoring capability for mccache

### ISSUE THREAD

**Issue by soichih** [soichih/meshconfig-admin#18]
Unlike mcpub / mcadmin, mccache service can not be tested for its status. I need to add monitoring capability so that any monitoring system can query for its status.

**Comment by soichih** [comment]
I've added a special api endpoint on mcadmin where mccache can report its caching status (at the end of caching) and updated mcadmin /health to analyze the cache status (see if it's fresh, and number of hosts cached). This should allow reliable monitoring of mccache through mcadmin service.

**Comment by soichih** [comment]
I just realized, I forgot to check for dynamic hosts updates. 

I should also display when was the last time the dynamci host was successfully updated (and alert user if it's stale?)

**Comment by ShawnMcKee** [comment]
Yes, I like the idea of being able to find stale hosts and tracking when updates are made.

**Comment by soichih** [comment]
I've added a check for dynamic host caching, and also added "stale" label on the host list. Closing this ticket.
