### ISSUE TITLE
MeshConfig import script

### ISSUE THREAD

**Issue by soichih** [soichih/meshconfig-admin#6]
Allow users to import existing meshconfig to recreate the MCA config. This requires all hosts to exist on MCA prior to import. We could either display warning that no all hosts can be added (and dump MCA hard-config-ed host list - once such feature is available?)

**Comment by ShawnMcKee** [comment]
This would be a very helpful addition.   Would it be possible to import (via meshconfig URL) and then create static entries for any missing hosts in MCA?

**Comment by ShawnMcKee** [comment]
Do you think ingesting a mesh via URL is going to be possible?  Some import option that takes a URL like: http://myosg.grid.iu.edu/psmesh/json/name/us-atlas 

This is becoming more important because of the need to have maddash.aglt2.org use meshconfig-itb.grid.iu.edu instead of myosg.grid.iu.edu;   I need to replicate ALL meshes from myosg into meshconfig-itb to allow proper operation of the ps-testbed mesh.  Right now ps-testbed hosts get their configuration from meshconfig-itb while maddash.aglt2.org's MaDDash is using myosg and the differences in configuration are breaking MaDDash's ability to get the right data.

**Comment by soichih** [comment]
I will try to implement the import feature tomorrow. 

It only took about 15 minutes to recreate /us-atlas meshconfig manually, so if you are in a hurry, I can I probably manually create all major meshconfigs that are currently listed in the MyOSG.

**Comment by soichih** [comment]
Shawn, I've implemented the importing feature and imported all meshconfig listed here (except "Dual-Stack Mesh Config". Is this mesh used?)
> http://myosg.grid.iu.edu/psmesh?count_sg_1&count_active=on&count_enabled=on
on meshconfig-itb.

Can you take a look?

**Comment by ShawnMcKee** [comment]
Thanks Soichi, I will look things over today and get  back to you.   Yes, the Dual-Stack Mesh config is in use.  It tracks our dual-stack setup (IPv4/IPv6) for various sites.

**Comment by ShawnMcKee** [comment]
Works great for me.  I was easily able to create a dual-stack mesh and import all the content from the myosg instance.  I will need to test the resulting meshes but I think this is working fine.

I realized that we will need to get current mesh-admins to sign up on the new meshconfig-itb (and eventually mesh-config).   I tried to add Duncan Rand as a mesh-admin for the imported dual-stack and (of course) he was registered.

**Comment by ShawnMcKee** [comment]
OK, so after I added the 2 requested new hosts to the BelleII mesh I want to the existing BelleII mesh in meshconfig-itb and tested what happens if I reimport.    

1) It creates new identical tests (so we end up with 2 Latency and 2 Bandwidth tests that look the same).

2) It only found 10 hosts for each mesh (matching the old configuration) when there are now 11 hosts in http://myosg.grid.iu.edu/psmesh/json/name/belleII

The 1) above is not really a problem but we should make it clear this is what will happen.    For 2) it must not be checking the current status when I click the import?

**Comment by soichih** [comment]
Shawn,

For 1), Should I prevent user from importing tests if there are tests with
the same name already exists?

For 2), The importer only create new hostgroup *if* there are no hostgroup
with the identical name exists. Meshconfig Admin allows user to *share* a
single hostgroup across multiple tests - rather than creating separate
hostgroup with identical list of hosts. To keep this behavior, I decided to
*key* hostgroup by its name when the importer tries to import hostgroup. In
this case, we already have "Belle II Bandwidth Mesh Group" and "Belle II
Latency Mesh Group" both with 10 hosts. This also minimizes *orphaned*
hostgroups that aren't used by any test.

When you tried re-importing the meshconfig, the importer saw that there are
hostgroups with the same names already existed (with 10 hosts) so it
skipped creating new hostgroups. Instead of skipping, we could *update* the
existing hostgroup, but there isn't a logical way to deal with added /
removed hosts (can you think of a clear rule?) Considering that importing
tool is only used rarely, I believe the best course of action is to
manually update the hostgroup once it's imported - rather than re-import
from the source. Do you agree?

Soichi

On Tue, Mar 21, 2017 at 8:38 AM Shawn McKee <notifications@github.com>
wrote:

OK, so after I added the 2 requested new hosts to the BelleII mesh I want
to the existing BelleII mesh in meshconfig-itb and tested what happens if I
reimport.

   1.

   It creates new identical tests (so we end up with 2 Latency and 2
   Bandwidth tests that look the same).
   2.

   It only found 10 hosts for each mesh (matching the old configuration)
   when there are now 11 hosts in
   http://myosg.grid.iu.edu/psmesh/json/name/belleII

The 1) above is not really a problem but we should make it clear this is
what will happen. For 2) it must not be checking the current status when I
click the import?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/soichih/meshconfig-admin/issues/6#issuecomment-288065694>,
or mute the thread

**Comment by ShawnMcKee** [comment]
Hi Soichi,

I think preventing import of already existing tests is likely a good idea.
The alternative would be to overwrite/replace but as you note, importing is
rare and manual updates are possible.

Yes, manually updating is fine.  I just wanted to understand how it worked.

Maybe when hostgroups and/or tests already exist it can just notify the
user that it is ignoring them and they should manually make any required
updates?

Thanks,

Shawn

**Comment by soichih** [comment]
I've added a bit more description on the UI

> This tool will register all missing hosts as adhoc hosts and register hostgroup, testspecs (if the same name doesn't exist already). Finally, it will create new meshconfig tests and populate here.

> Meshconfig tests themselves won't be registered automatically - until you click Update on this pageIIf you import the same meshconfig twice, already imported test won't be overriden - you need to remove old tests manually

I hope this will be clear enough to the users.
