### ISSUE TITLE
Add pagination / search capability under host page

### ISSUE THREAD

**Issue by soichih** [soichih/meshconfig-admin#8]
Hosts page is very primitive, and slow to render due to large number of hosts displayed. I should add pagination features, and I should also add some form of searching capability so that user can easily search hosts.

**Comment by ShawnMcKee** [comment]
I would additionally request the ability to filter.   For example, I just want to see all hosts that list a community of 'ATLAS'.   Note:  possible complication is that those configuring communities might use 'Atlas' or 'atlas' or even 'ATlas', etc.

**Comment by soichih** [comment]
I've added host filter. It works in somewhat perculier way, but I will adjust the filtering logic if you find it annoying. Please play with it and see. The query will be persisted in cookie.

**Comment by soichih** [comment]
I've added ffilter for hostgroups and testspecs page also.
